[package]
name = "ergodic"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio  = { version = "1.37", features = ["rt-multi-thread", "macros"] }
axum   = "0.7"
serde  = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam = { version = "0.8" }
crossbeam-channel = "0.5"  